### ISSUE TITLE
ADK 2004 is supported?

### ISSUE THREAD

**Issue by tahakogi** [MicrosoftDocs/memdocs.ja-jp#4]
[フィードバックをこちらに入力してください]
Windows ADK for Windows 10 ver 2004 is released.
Is this version supported or not?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ce35f51b-8368-6cfa-868c-404a3e533b67
* Version Independent ID: f4b5e0ed-226f-5811-dfa0-628bf57a0bbd
* Content: [Windows 10 のサポート - Configuration Manager](https://docs.microsoft.com/ja-jp/mem/configmgr/core/plan-design/configs/support-for-windows-10)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-windows-10.md](https://github.com/MicrosoftDocs/memdocs.ja-jp/blob/live/memdocs/configmgr/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by srvbpigh** [comment]
Hello, @tahakogi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @tahakogi, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/memdocs/issues/293. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
